services:
  - type: web
    name: copynova-telegram-service
    env: python
    region: singapore
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app -w 1 --timeout 120 --graceful-timeout 30
    envVars:
      - key: TELEGRAM_API_ID
        value: "23111641"
      - key: TELEGRAM_API_HASH
        value: "6288120282735bf0fecc4753ee60b1b8"
      - key: PYTHONUNBUFFERED
        value: "true"
      - key: PYTHON_VERSION
        value: "3.12.11"
